export interface NameOfAllah {
  id: number;
  arabic: string;
  transliteration: string;
  meaning: string;
  meaningUrdu: string;
}

export const asmaUlHusna: NameOfAllah[] = [
  { id: 1, arabic: "الرَّحْمَنُ", transliteration: "Ar-Rahman", meaning: "The Most Gracious", meaningUrdu: "سب سے زیادہ رحم کرنے والا" },
  { id: 2, arabic: "الرَّحِيمُ", transliteration: "Ar-Raheem", meaning: "The Most Merciful", meaningUrdu: "بہت زیادہ رحم والا" },
  { id: 3, arabic: "الْمَلِكُ", transliteration: "Al-Malik", meaning: "The King", meaningUrdu: "بادشاہ" },
  { id: 4, arabic: "الْقُدُّوسُ", transliteration: "Al-Quddus", meaning: "The Most Holy", meaningUrdu: "بے عیب پاک" },
  { id: 5, arabic: "السَّلَامُ", transliteration: "As-Salam", meaning: "The Source of Peace", meaningUrdu: "سلامت کا ذریعہ" },
  { id: 6, arabic: "الْمُؤْمِنُ", transliteration: "Al-Mu'min", meaning: "The Guardian of Faith", meaningUrdu: "ایمان دہندہ" },
  { id: 7, arabic: "الْمُهَيْمِنُ", transliteration: "Al-Muhaymin", meaning: "The Protector", meaningUrdu: "حفاظت کرنے والا" },
  { id: 8, arabic: "الْعَزِيزُ", transliteration: "Al-Aziz", meaning: "The Almighty", meaningUrdu: "شکست نہ پذیر" },
  { id: 9, arabic: "الْجَبَّارُ", transliteration: "Al-Jabbar", meaning: "The Compeller", meaningUrdu: "طاقت والا" },
  { id: 10, arabic: "الْمُتَكَبِّرُ", transliteration: "Al-Mutakabbir", meaning: "The Supreme", meaningUrdu: "بزرگیت والا" },
  { id: 11, arabic: "الْخَالِقُ", transliteration: "Al-Khaliq", meaning: "The Creator", meaningUrdu: "پیدا کرنے والا" },
  { id: 12, arabic: "الْبَارِئُ", transliteration: "Al-Bari", meaning: "The Maker", meaningUrdu: "تخلیق کرنے والا" },
  { id: 13, arabic: "الْمُصَوِّرُ", transliteration: "Al-Musawwir", meaning: "The Fashioner", meaningUrdu: "شکل دینے والا" },
  { id: 14, arabic: "الْغَفَّارُ", transliteration: "Al-Ghaffar", meaning: "The Forgiver", meaningUrdu: "بخششنے والا" },
  { id: 15, arabic: "الْقَهَّارُ", transliteration: "Al-Qahhar", meaning: "The Subduer", meaningUrdu: "غلابی دینے والا" },
  { id: 16, arabic: "الْوَهَّابُ", transliteration: "Al-Wahhab", meaning: "The Bestower", meaningUrdu: "عطا کرنے والا" },
  { id: 17, arabic: "الرَّزَّاقُ", transliteration: "Ar-Razzaq", meaning: "The Provider", meaningUrdu: "روزی دینے والا" },
  { id: 18, arabic: "الْفَتَّاحُ", transliteration: "Al-Fattah", meaning: "The Opener", meaningUrdu: "کھولنے والا" },
  { id: 19, arabic: "الْعَلِيْمُ", transliteration: "Al-Aleem", meaning: "The All-Knowing", meaningUrdu: "سب جاننے والا" },
  { id: 20, arabic: "الْقَاضِي", transliteration: "Al-Qaadi", meaning: "The Judge", meaningUrdu: "فيصلہ کرنے والا" },
  { id: 21, arabic: "الشَّهِيدُ", transliteration: "Ash-Shaheed", meaning: "The Witness", meaningUrdu: "گواہی دینے والا" },
  { id: 22, arabic: "الْحَقُّ", transliteration: "Al-Haqq", meaning: "The Truth", meaningUrdu: "سچا" },
  { id: 23, arabic: "الْوَكِيلُ", transliteration: "Al-Wakeel", meaning: "The Trustee", meaningUrdu: "وکیل" },
  { id: 24, arabic: "الْقَوِيُّ", transliteration: "Al-Qawiyy", meaning: "The Most Strong", meaningUrdu: "سب سے زیادہ طاقت والا" },
  { id: 25, arabic: "الْمَتِينُ", transliteration: "Al-Mateen", meaning: "The Firm", meaningUrdu: "مضبوط" },
  { id: 26, arabic: "الْوَلِيُّ", transliteration: "Al-Waliyy", meaning: "The Protector", meaningUrdu: "دوست والا" },
  { id: 27, arabic: "الْحَمِيدُ", transliteration: "Al-Hameed", meaning: "The Praiseworthy", meaningUrdu: "تعریف کے لائق" },
  { id: 28, arabic: "الْمُحْصِي", transliteration: "Al-Muhsee", meaning: "The Counter", meaningUrdu: "شمار کرنے والا" },
  { id: 29, arabic: "الْمُبْدِئُ", transliteration: "Al-Mubdi", meaning: "The Originator", meaningUrdu: "ابتدا کرنے والا" },
  { id: 30, arabic: "الْمُعِيدُ", transliteration: "Al-Mueed", meaning: "The Restorer", meaningUrdu: "واپس لانے والا" },
  { id: 31, arabic: "الْمُحْيِي", transliteration: "Al-Muhyi", meaning: "The Giver of Life", meaningUrdu: "زندگی دینے والا" },
  { id: 32, arabic: "الْمُمِيتُ", transliteration: "Al-Mumeet", meaning: "The Bringer of Death", meaningUrdu: "موت دینے والا" },
  { id: 33, arabic: "الْحَيُّ", transliteration: "Al-Hayy", meaning: "The Ever-Living", meaningUrdu: "ہمیشہ زندہ" },
  { id: 34, arabic: "الْقَيُّومُ", transliteration: "Al-Qayyum", meaning: "The Self-Sustaining", meaningUrdu: "قائم بذات" },
  { id: 35, arabic: "الْوَاجِدُ", transliteration: "Al-Wajid", meaning: "The Perceiver", meaningUrdu: "پانے والا" },
  { id: 36, arabic: "الْمَاجِدُ", transliteration: "Al-Majid", meaning: "The Illustrious", meaningUrdu: "بزرگ و شریف" },
  { id: 37, arabic: "الْوَاحِدُ", transliteration: "Al-Wahid", meaning: "The One", meaningUrdu: "ایک" },
  { id: 38, arabic: "الصَّمَدُ", transliteration: "As-Samad", meaning: "The Eternal", meaningUrdu: "بے نیاز" },
  { id: 39, arabic: "الْقَادِرُ", transliteration: "Al-Qadir", meaning: "The Capable", meaningUrdu: "قدرت والا" },
  { id: 40, arabic: "الْمُقْتَدِرُ", transliteration: "Al-Muqtadir", meaning: "The Omnipotent", meaningUrdu: "مکمل قدرت والا" },
  { id: 41, arabic: "الْمُقَدِّمُ", transliteration: "Al-Muqaddim", meaning: "The Advancer", meaningUrdu: "آگے کرنے والا" },
  { id: 42, arabic: "الْمُؤَخِّرُ", transliteration: "Al-Mu'akhkhir", meaning: "The Delayer", meaningUrdu: "پیچھے کرنے والا" },
  { id: 43, arabic: "الْأَوَّلُ", transliteration: "Al-Awwal", meaning: "The First", meaningUrdu: "پہلا" },
  { id: 44, arabic: "الْآخِرُ", transliteration: "Al-Aakhir", meaning: "The Last", meaningUrdu: "آخری" },
  { id: 45, arabic: "الظَّاهِرُ", transliteration: "Az-Zaahir", meaning: "The Manifest", meaningUrdu: "ظاہر" },
  { id: 46, arabic: "الْبَاطِنُ", transliteration: "Al-Baatin", meaning: "The Hidden", meaningUrdu: "پوشیدہ" },
  { id: 47, arabic: "الْوَالِي", transliteration: "Al-Waali", meaning: "The Governor", meaningUrdu: "حاکم" },
  { id: 48, arabic: "الْمُتَعَالِي", transliteration: "Al-Muta'ali", meaning: "The Most Exalted", meaningUrdu: "بہت بلند" },
  { id: 49, arabic: "الْبَرُّ", transliteration: "Al-Barr", meaning: "The Source of Goodness", meaningUrdu: "نیکی کا ذریعہ" },
  { id: 50, arabic: "التَّوَّابُ", transliteration: "At-Tawwab", meaning: "The Acceptor of Repentance", meaningUrdu: "توبہ قبول کرنے والا" },
  { id: 51, arabic: "الْمُنْتَقِمُ", transliteration: "Al-Muntaqim", meaning: "The Avenger", meaningUrdu: "انتقام لینے والا" },
  { id: 52, arabic: "الْعَفُوُّ", transliteration: "Al-Afuww", meaning: "The Pardoner", meaningUrdu: "معاف کرنے والا" },
  { id: 53, arabic: "الرَّؤُوفُ", transliteration: "Ar-Raoof", meaning: "The Kind", meaningUrdu: "نرم دل" },
  { id: 54, arabic: "مَالِكُ الْمُلْكِ", transliteration: "Malik ul-Mulk", meaning: "Owner of Sovereignty", meaningUrdu: "بادشاہت کا مالک" },
  { id: 55, arabic: "ذُو الْجَلَالِ وَالْإِكْرَامِ", transliteration: "Dhul-Jalali wal-Ikram", meaning: "Lord of Majesty", meaningUrdu: "عظمت و بزرگی والا" },
  { id: 56, arabic: "الْمُقْسِطُ", transliteration: "Al-Muqsit", meaning: "The Equitable", meaningUrdu: "انصاف کرنے والا" },
  { id: 57, arabic: "الْجَامِعُ", transliteration: "Al-Jaami", meaning: "The Gatherer", meaningUrdu: "جمع کرنے والا" },
  { id: 58, arabic: "الْغَنِيُّ", transliteration: "Al-Ghaniyy", meaning: "The Self-Sufficient", meaningUrdu: "بے نیاز" },
  { id: 59, arabic: "الْمُغْنِي", transliteration: "Al-Mughni", meaning: "The Enricher", meaningUrdu: "غیبی دینے والا" },
  { id: 60, arabic: "الْمَانِعُ", transliteration: "Al-Mani", meaning: "The Withholder", meaningUrdu: "روکنے والا" },
  { id: 61, arabic: "الضَّارُّ", transliteration: "Ad-Daarr", meaning: "The Distresser", meaningUrdu: "نقصان دینے والا" },
  { id: 62, arabic: "النَّافِعُ", transliteration: "An-Naafi", meaning: "The Benefactor", meaningUrdu: "فائدہ دینے والا" },
  { id: 63, arabic: "النُّورُ", transliteration: "An-Noor", meaning: "The Light", meaningUrdu: "روشنی" },
  { id: 64, arabic: "الْهَادِي", transliteration: "Al-Haadi", meaning: "The Guide", meaningUrdu: "رہنمائی کرنے والا" },
  { id: 65, arabic: "الْبَدِيعُ", transliteration: "Al-Badee", meaning: "The Incomparable", meaningUrdu: "نایاب" },
  { id: 66, arabic: "الْبَاقِي", transliteration: "Al-Baaqi", meaning: "The Everlasting", meaningUrdu: "ہمیشہ رہنے والا" },
  { id: 67, arabic: "الْوَارِثُ", transliteration: "Al-Waarith", meaning: "The Inheritor", meaningUrdu: "وارث" },
  { id: 68, arabic: "الرَّشِيدُ", transliteration: "Ar-Rasheed", meaning: "The Guide to the Right Path", meaningUrdu: "راست راہ دکھانے والا" },
  { id: 69, arabic: "الصَّبُورُ", transliteration: "As-Saboor", meaning: "The Patient", meaningUrdu: "صبر کرنے والا" },
];
