export interface NameOfAllah {
  id: number;
  arabic: string;
  transliteration: string;
  meaning: string;
}

export const asmaUlHusna: NameOfAllah[] = [
  { id: 1, arabic: "الرَّحْمَنُ", transliteration: "Ar-Rahman", meaning: "The Most Gracious" },
  { id: 2, arabic: "الرَّحِيمُ", transliteration: "Ar-Raheem", meaning: "The Most Merciful" },
  { id: 3, arabic: "المَلِكُ", transliteration: "Al-Malik", meaning: "The King" },
  { id: 4, arabic: "الْقُدّوسُ", transliteration: "Al-Quddus", meaning: "The Most Holy" },
  { id: 5, arabic: "السَّلَامُ", transliteration: "As-Salam", meaning: "The Source of Peace" },
  { id: 6, arabic: "الْمُؤْمِنُ", transliteration: "Al-Mu'min", meaning: "The Guardian of Faith" },
  { id: 7, arabic: "الْمُهَيْمِنُ", transliteration: "Al-Muhaymin", meaning: "The Protector" },
  { id: 8, arabic: "الْعَزِيزُ", transliteration: "Al-Aziz", meaning: "The Almighty" },
  { id: 9, arabic: "الجَبَّارُ", transliteration: "Al-Jabbar", meaning: "The Compeller" },
  { id: 10, arabic: "الْمُتَكَبِّرُ", transliteration: "Al-Mutakabbir", meaning: "The Supreme" },
  { id: 11, arabic: "الْخَالِقُ", transliteration: "Al-Khaliq", meaning: "The Creator" },
  { id: 12, arabic: "الْبَارِئُ", transliteration: "Al-Bari", meaning: "The Maker" },
  { id: 13, arabic: "الْمُصَوِّرُ", transliteration: "Al-Musawwir", meaning: "The Fashioner" },
  { id: 14, arabic: "الْغَفَّارُ", transliteration: "Al-Ghaffar", meaning: "The Forgiver" },
  { id: 15, arabic: "الْقَهَّارُ", transliteration: "Al-Qahhar", meaning: "The Subduer" },
  { id: 16, arabic: "الْوَهَّابُ", transliteration: "Al-Wahhab", meaning: "The Bestower" },
  { id: 17, arabic: "الرَّزَّاقُ", transliteration: "Ar-Razzaq", meaning: "The Provider" },
  { id: 18, arabic: "الْفَتَّاحُ", transliteration: "Al-Fattah", meaning: "The Opener" },
  { id: 19, arabic: "الْعَلِيْمُ", transliteration: "Al-Aleem", meaning: "The All-Knowing" },
  { id: 20, arabic: "الْقَاضِي", transliteration: "Al-Qaadi", meaning: "The Judge" },
  { id: 21, arabic: "الشَّهِيدُ", transliteration: "Ash-Shaheed", meaning: "The Witness" },
  { id: 22, arabic: "الْحَقُّ", transliteration: "Al-Haqq", meaning: "The Truth" },
  { id: 23, arabic: "الْوَكِيلُ", transliteration: "Al-Wakeel", meaning: "The Trustee" },
  { id: 24, arabic: "الْقَوِيُّ", transliteration: "Al-Qawiyy", meaning: "The Most Strong" },
  { id: 25, arabic: "المَتِينُ", transliteration: "Al-Mateen", meaning: "The Firm" },
  { id: 26, arabic: "وَلِيُّ", transliteration: "Al-Waliyy", meaning: "The Patron" },
  { id: 27, arabic: "الْحَمِيدُ", transliteration: "Al-Hameed", meaning: "The Praiseworthy" },
  { id: 28, arabic: "الْمُحْصِي", transliteration: "Al-Muhsee", meaning: "The Counter" },
  { id: 29, arabic: "الْمُبْدِئُ", transliteration: "Al-Mubdi", meaning: "The Originator" },
  { id: 30, arabic: "الْمُعِيدُ", transliteration: "Al-Mueed", meaning: "The Restorer" },
  { id: 31, arabic: "الْمُحْيِي", transliteration: "Al-Muhyee", meaning: "The Giver of Life" },
  { id: 32, arabic: "الْمُمِيتُ", transliteration: "Al-Mumeet", meaning: "The Bringer of Death" },
  { id: 33, arabic: "الْحَيُّ", transliteration: "Al-Hayy", meaning: "The Ever-Living" },
  { id: 34, arabic: "الْقَيُّمُ", transliteration: "Al-Qayyoom", meaning: "The Self-Sustaining" },
  { id: 35, arabic: "الْوَاجِدُ", transliteration: "Al-Waajid", meaning: "The Perceiver" },
  { id: 36, arabic: "المَاجِدُ", transliteration: "Al-Maajid", meaning: "The Illustrious" },
  { id: 37, arabic: "الواحِدُ", transliteration: "Al-Waahid", meaning: "The One" },
  { id: 38, arabic: "الصَّمَدُ", transliteration: "As-Samad", meaning: "The Eternal" },
  { id: 39, arabic: "الْقَادِرُ", transliteration: "Al-Qadir", meaning: "The Capable" },
  { id: 40, arabic: "الْمُقْتَدِرُ", transliteration: "Al-Muqtadir", meaning: "The Omnipotent" },
  { id: 41, arabic: "الْمُقَدِّمُ", transliteration: "Al-Muqaddim", meaning: "The Advancer" },
  { id: 42, arabic: "الْمُؤَخِّرُ", transliteration: "Al-Mu'akhkhir", meaning: "The Delayer" },
  { id: 43, arabic: "الأَوَّلُ", transliteration: "Al-Awwal", meaning: "The First" },
  { id: 44, arabic: "الآخِرُ", transliteration: "Al-Aakhir", meaning: "The Last" },
  { id: 45, arabic: "الظَّاهِرُ", transliteration: "Az-Zaahir", meaning: "The Manifest" },
  { id: 46, arabic: "البَاطِنُ", transliteration: "Al-Baatin", meaning: "The Hidden" },
  { id: 47, arabic: "الْوَالِي", transliteration: "Al-Waali", meaning: "The Governor" },
  { id: 48, arabic: "الْمُتَعَالِي", transliteration: "Al-Muta'aali", meaning: "The Most Exalted" },
  { id: 49, arabic: "البَّرُّ", transliteration: "Al-Barr", meaning: "The Source of Goodness" },
  { id: 50, arabic: "التَّوَّابُ", transliteration: "At-Tawwaab", meaning: "The Acceptor of Repentance" },
  { id: 51, arabic: "الْمُنتَقِمُ", transliteration: "Al-Muntaqim", meaning: "The Avenger" },
  { id: 52, arabic: "عَفُوٌّ", transliteration: "Afuww", meaning: "The Pardoner" },
  { id: 53, arabic: "رَؤُوفٌ", transliteration: "Ra'oof", meaning: "The Kind" },
  { id: 54, arabic: "مَالِكُ الْمُلْكِ", transliteration: "Maalik-ul-Mulk", meaning: "Owner of Sovereignty" },
  { id: 55, arabic: "ذُولْجَلَالِ وَالِإِكْرَامِ", transliteration: "Dhul-Jalaali wal-Ikraam", meaning: "Lord of Majesty" },
  { id: 56, arabic: "الْمُقْسِطُ", transliteration: "Al-Muqsit", meaning: "The Equitable" },
  { id: 57, arabic: "الجَامِعُ", transliteration: "Al-Jaami'", meaning: "The Gatherer" },
  { id: 58, arabic: "الغَنِيُّ", transliteration: "Al-Ghaniyy", meaning: "The Self-Sufficient" },
  { id: 59, arabic: "الْمُغْنِيُ", transliteration: "Al-Mughni", meaning: "The Enricher" },
  { id: 60, arabic: "المَانِعُ", transliteration: "Al-Maani'", meaning: "The Withholder" },
  { id: 61, arabic: "الضَّارُّ", transliteration: "Ad-Daarr", meaning: "The Distresser" },
  { id: 62, arabic: "النَّافِعُ", transliteration: "An-Naafi'", meaning: "The Benefactor" },
  { id: 63, arabic: "النُوُّرُ", transliteration: "An-Noor", meaning: "The Light" },
  { id: 64, arabic: "الهَادِي", transliteration: "Al-Haadi", meaning: "The Guide" },
  { id: 65, arabic: "البَدِيعُ", transliteration: "Al-Badee'", meaning: "The Incomparable" },
  { id: 66, arabic: "البَاقِي", transliteration: "Al-Baaqi", meaning: "The Everlasting" },
  { id: 67, arabic: "الوَارِثُ", transliteration: "Al-Waarith", meaning: "The Inheritor" },
  { id: 68, arabic: "الرَّشِيدُ", transliteration: "Ar-Rasheed", meaning: "The Guide to the Right Path" },
  { id: 69, arabic: "الصَّبِيرُ", transliteration: "As-Saboor", meaning: "The Patient" },
  { id: 70, arabic: "وَسِعُ", transliteration: "Wasi'", meaning: "The All-Encompassing" },
  { id: 71, arabic: "الحَكِيمُ", transliteration: "Al-Hakeem", meaning: "The Wise" },
  { id: 72, arabic: "الخَبِيرُ", transliteration: "Al-Khabeer", meaning: "The All-Aware" },
  { id: 73, arabic: "اللَّطِيفُ", transliteration: "Al-Lateef", meaning: "The Subtle" },
  { id: 74, arabic: "الخبيرُ", transliteration: "Al-Khabeer", meaning: "The Aware" },
  { id: 75, arabic: "الحلِيمُ", transliteration: "Al-Haleem", meaning: "The Forbearing" },
  { id: 76, arabic: "العظِيمُ", transliteration: "Al-Azeem", meaning: "The Magnificent" },
  { id: 77, arabic: "الغَفُورُ", transliteration: "Al-Ghafoor", meaning: "The Forgiving" },
  { id: 78, arabic: "الشَّكُورُ", transliteration: "Ash-Shakoor", meaning: "The Appreciative" },
  { id: 79, arabic: "العَلِيُّ", transliteration: "Al-Alee", meaning: "The Most High" },
  { id: 80, arabic: "الكَبِيرُ", transliteration: "Al-Kabeer", meaning: "The Great" },
  { id: 81, arabic: "الحَفِيظُ", transliteration: "Al-Hafeez", meaning: "The Preserver" },
  { id: 82, arabic: "المُقِيتُ", transliteration: "Al-Muqeet", meaning: "The Nourisher" },
  { id: 83, arabic: "الحَسِيبُ", transliteration: "Al-Haseeb", meaning: "The Reckoner" },
  { id: 84, arabic: "الجَلِيلُ", transliteration: "Al-Jaleel", meaning: "The Majestic" },
  { id: 85, arabic: "الكَرِيمُ", transliteration: "Al-Kareem", meaning: "The Generous" },
  { id: 86, arabic: "الرَّقِيبُ", transliteration: "Ar-Raqeeb", meaning: "The Watchful" },
  { id: 87, arabic: "المُجِيبُ", transliteration: "Al-Mujeeb", meaning: "The Responsive" },
  { id: 88, arabic: "الوَاسِعُ", transliteration: "Al-Waasi'", meaning: "The Vast" },
  { id: 89, arabic: "الحكِيمُ", transliteration: "Al-Hakeem", meaning: "The Wise" },
  { id: 90, arabic: "الوَدُودُ", transliteration: "Al-Wudoood", meaning: "The Loving" },
  { id: 91, arabic: "المَجِيدُ", transliteration: "Al-Majeed", meaning: "The Glorious" },
  { id: 92, arabic: "بَاعِثُ الْحُمْنَاءِ", transliteration: "Baa'ithul-Humamaa", meaning: "The Resurrector" },
  { id: 93, arabic: "الشَّهِيدُ", transliteration: "Ash-Shaheed", meaning: "The Witness" },
  { id: 94, arabic: "الحَقُّ", transliteration: "Al-Haqq", meaning: "The Truth" },
  { id: 95, arabic: "الوَكِيلُ", transliteration: "Al-Wakeel", meaning: "The Trustee" },
  { id: 96, arabic: "الْقَوِيُّ", transliteration: "Al-Qawiyy", meaning: "The Strong" },
  { id: 97, arabic: "المَتِينُ", transliteration: "Al-Mateen", meaning: "The Firm" },
  { id: 98, arabic: "وَلِيُّ", transliteration: "Al-Waliyy", meaning: "The Protector" },
  { id: 99, arabic: "الحَمِيدُ", transliteration: "Al-Hameed", meaning: "The Praiseworthy" },
];
